name: Deply web through surge with G-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
        with:
          node-version: 12
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./ github-workflow-g-action-surge.surge.sh --token ${{Secret.SURGE_TOKEN}}       
          
